import type { FurnitureType } from '../../model/decor'
import { PLY, BLACK, finish, BODY_FINISHES, METAL_FINISHES, type FurnitureSpec, roundMm } from './spec'

// Pieces that hang on a wall or from the ceiling.

export const KITCHEN_WALL = {
  mugs: {
    label: 'Ceramic mugs',
    note: 'Speckled stoneware, a few colors',
    group: 'Kitchen & wall',
    mount: 'surface',
    tabletop: true,
    size: [0.44, 0.1, 0.15],
    sizeFor: (o, s) => [roundMm(Math.max(1, Math.min(6, Math.round(Number(o.count ?? 4)))) * 0.11), s[1], s[2]],
    uses: ['body'],
    finish: finish(BODY_FINISHES[1].color),
    options: { count: 4, glaze: 'mixed', tray: false },
    optionSpecs: [
      { key: 'count', label: 'Mugs', kind: 'range', min: 1, max: 6, step: 1 },
      { key: 'tray', label: 'On a wood tray', kind: 'toggle' },
      {
        key: 'glaze',
        label: 'Glaze',
        kind: 'chips',
        choices: [
          { id: 'mixed', label: 'Mixed colors' },
          { id: 'speckled', label: 'Speckled oat' },
          { id: 'white', label: 'Glossy white' },
        ],
      },
    ],
    editable: [],
  },
  gridShelf: {
    label: 'Grid wall shelf',
    note: 'Black steel frame, wood shelves',
    group: 'Kitchen & wall',
    mount: 'wall',
    size: [1.2, 0.9, 0.28],
    uses: ['body', 'metal'],
    finish: finish(BODY_FINISHES[1].color, BLACK),
    options: { shelves: 3 },
    optionSpecs: [{ key: 'shelves', label: 'Shelves', kind: 'range', min: 2, max: 5, step: 1 }],
    editable: ['w', 'h', 'd'],
  },
  upperCabinets: {
    label: 'Reeded glass cabinets',
    note: 'Sliding doors on a rail, LED below',
    group: 'Kitchen & wall',
    mount: 'wall',
    size: [1.45, 0.7, 0.34],
    uses: ['body', 'metal'],
    finish: finish(BODY_FINISHES[1].color, BLACK),
    options: { led: true, glass: 'reeded' },
    optionSpecs: [
      {
        key: 'glass',
        label: 'Glass',
        kind: 'chips',
        choices: [
          { id: 'reeded', label: 'Reeded' },
          { id: 'wired', label: 'Wired' },
          { id: 'clear', label: 'Clear' },
        ],
      },
      { key: 'led', label: 'LED strip underneath', kind: 'toggle' },
    ],
    editable: ['w', 'h', 'd'],
  },
  floatingShelf: {
    label: 'Floating shelf',
    note: 'Solid wood on brackets',
    group: 'Kitchen & wall',
    mount: 'wall',
    size: [0.9, 0.035, 0.22],
    uses: ['body', 'metal'],
    finish: finish(BODY_FINISHES[1].color, BLACK),
    options: { brackets: true, items: false },
    optionSpecs: [
      { key: 'brackets', label: 'Visible brackets', kind: 'toggle' },
      { key: 'items', label: 'Styled: mugs, jars, books, a plant', kind: 'toggle' },
    ],
    editable: ['w', 'd'],
  },
  pegGrid: {
    label: 'Wire grid',
    note: 'With S-hooks and utensils',
    group: 'Kitchen & wall',
    mount: 'wall',
    size: [0.9, 0.6, 0.02],
    uses: ['metal'],
    finish: finish(PLY, BLACK),
    options: { utensils: true },
    optionSpecs: [{ key: 'utensils', label: 'Hanging utensils', kind: 'toggle' }],
    editable: ['w', 'h'],
  },
  kitchenRail: {
    label: 'Rail',
    note: 'Hook rail or knife strip',
    group: 'Kitchen & wall',
    mount: 'wall',
    size: [0.6, 0.03, 0.04],
    uses: ['metal'],
    finish: finish(PLY, METAL_FINISHES[3].color),
    options: { variant: 'hooks' },
    optionSpecs: [
      {
        key: 'variant',
        label: 'Type',
        kind: 'chips',
        choices: [
          { id: 'hooks', label: 'Hooks + tools' },
          { id: 'knives', label: 'Knife strip' },
        ],
      },
    ],
    editable: ['w'],
  },
  fruitBaskets: {
    label: 'Fruit baskets',
    note: '3-tier wire, on the wall',
    group: 'Kitchen & wall',
    mount: 'wall',
    size: [0.42, 0.72, 0.24],
    uses: ['metal'],
    finish: finish(),
    options: { fruit: true },
    optionSpecs: [{ key: 'fruit', label: 'Filled with fruit', kind: 'toggle' }],
    editable: [],
  },
  hangingRack: {
    label: 'Ceiling grid rack',
    note: 'On chains, for plants and pans',
    group: 'Kitchen & wall',
    mount: 'ceiling',
    size: [0.9, 0.6, 0.45],
    uses: ['metal'],
    finish: finish(),
    options: {},
    optionSpecs: [],
    editable: ['w', 'h', 'd'],
  },
} satisfies Partial<Record<FurnitureType, FurnitureSpec>>
